FROM toposoid/python-nlp-japanese:0.5-SNAPSHOT###SPEC_LEVEL###

ARG TARGET_BRANCH
ARG SENTENCE_TRANSFORMER_MODEL
ARG VECTOR_MODEL

WORKDIR /app
ENV DEPLOYMENT=local

RUN apt-get update \
&& apt-get -y install git \
&& git clone https://github.com/toposoid/toposoid-common-nlp-japanese-web.git \
&& cd toposoid-common-nlp-japanese-web \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH} \
&& pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt \
&& mv -f /tmp/entity_vector.model.bin ./ \
&& mv -f /tmp/wnjpn.db ./ \
&& mv -f /tmp/chive-1.2-mc${VECTOR_MODEL}.kv ./ \
&& mv -f /tmp/chive-1.2-mc${VECTOR_MODEL}.kv.vectors.npy ./ \
&& mkdir -p models \
&& mkdir -p models/sentence-transformers_${SENTENCE_TRANSFORMER_MODEL} \
&& mv -f /tmp/${SENTENCE_TRANSFORMER_MODEL}/* ./models/sentence-transformers_${SENTENCE_TRANSFORMER_MODEL}/ \
&& rm -Rf /tmp/*
